framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        # Désactive le polyfill es-module-shims (source des warnings "import map rule was removed")
        importmap_polyfill: false
        importmap_script_attributes:
            id: importmap
            data-turbo-permanent: ''

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
